- name: Install Misc apt packages
  apt: pkg={{ item }} state=latest
  with_items:
      - meld # file comparison
      - okular # pdfs
      - libreoffice
      - fdupes # clear duplicate files
      - fslint # same as above
      - rdesktop
      - kdeconnect # occasionally useful for file transfer; etc. Should be swapped for QR file transfer repo.
      - gwenview
      - shellcheck # to make us not suck at Bash; in future look into https://github.com/mvdan/sh shell formatters

- include_role:
      name: wisc-vpn

- include_role:
      name: iknite.spotify

- include_role:
      name: virtual-box

- include_role:
      name: dotfiles

- include_role:
      name: cron

# TODO: remove annoying ubuntu default packages
# TODO: blacklist ubuntu packages?
# for both of these check the file in this directory for sample

# TODO: find a mail client we don't dislike
#
# TODO: install the tool that collects TODO messages as a
# todolist, also the repo jumping tool, and anything else
# that helps us move better and be better organized in our repos.

