---
- name: Dotfiles clone repo
  git:
    repo: "{{ dotfiles_repo }}"
    clone: yes
    dest: ~/{{ dotfiles_repo_name }}

- name: Dotfiles run install script
  command: bash ~/{{ dotfiles_repo_name }}/install_script.sh
