---
# https://itsfoss.com/backup-restore-linux-timeshift/
- name: Timeshift add repository
  apt_repository:
      repo: 'ppa:teejee2008/ppa'
    state: present
    update_cache: yes

- name: Timeshift installation
  apt:
    name: timeshift
    state: present
