# https://github.com/balena-io/etcher
- name: Etcher add key
  apt_key:
      keyserver: hkp://pgp.mit.edu:80
      id: 379CE192D401AB61
      state: present

- name: Etcher add repository
  apt_repository:
      repo: deb https://dl.bintray.com/resin-io/debian stable etcher
      filename: /etc/apt/sources.list.d/etcher.list
      state: present
      update_cache: yes

- name: Etcher installation
  apt:
      name: etcher-electron
      state: present
